### ISSUE TITLE
Move teach.mozilla.org to learning.mozilla.org

### ISSUE THREAD

**Issue by xmatthewx** [MozillaFoundation/mofo-devops#310]
Cassie & Claw decided that we will move the teach site to learning dot mozilla.

### Risks

Are there any blockers? Are there any risks? 

@kristinashu @sabrinang – is there any text or design that might confuse the user? Places where we refer to "teach".

@Pomax @simonwex – are there any links or dependencies that might break? (Anyone else familiar with the site who should comment?)

@ldecoursy – Old links will forward to new address. An announcement to community probably isn't required. True? 

### Tasks

 - [x] Acquire SSL certificate for `learning.mozilla.org`
 - [x] Create cloudfront CDN that uses above cert, point it at the teach site content served on Heroku.
 - [x] File IT bug to direct `learning.mozilla.org` to the above CDN
 - [x] modify the origin that the current teach site uses to be an s3 redirect to `learning.mozilla.org`
 - [x] Update OAuth configuration for new hostname ( auth Callback url )

@cadecairos – we are good to go if we get a thumbs up from design, tech, and program. 

cc @hannahkane

**Comment by sabrinang** [comment]
I think the main places where we refer to teach are on social channels (@MozTeach), hashtags (#teachtheweb #TTWChat), emails, teaching activities and club guides. Also, on some of those materials I have seen the abbreviation MLN on them but without context of what that abbreviation means. I don't think much design is affected since we purposely kept it generic until things have settled but mainly text in comms materials are inconsistent that confuses the user.

There was good feedback from a community member that highlighted this a while back when we tried to address this: https://github.com/mozilla/teach.mozilla.org/issues/1658#issuecomment-187243031

**Comment by cadecairos** [comment]
We'll need to update the OAuth client record on id.webmaker.org with a new callback url. We'll also need an SSL certificate. 

We can redirect teach.Mozilla.org and preserve URL paths fairly easily using cloudfront+S3.

**Comment by mmmavis** [comment]
tagging @adamlofting here to see if this will affect our Google Analytics data

**Comment by adamlofting** [comment]
:+1: @mmmavis :raised_hands: - I'm so happy someone asked that question!

Though, in this case, we haven't filtered the reports by domain name, so it's safe to switch at any time. Generally we'd need to update the filters in GA to allow a new domain through.

**Comment by xmatthewx** [comment]
Wow. The team parachutes in for speedy triage. Thanks all.

**Comment by Pomax** [comment]
On a loosely related note, was there a rationale for the change? I'm interested in why we went from an action verb to a nominative for the key identifier (action verbs feel like they work much better for people to remember and identify with, so if that's wrong intuition, I'd love to learn about that =)

**Comment by ldecoursy** [comment]
It's based on the recent [IA work](https://docs.google.com/presentation/d/1MOhf0PSvCU2flniNsbl1FW0xPi0ZnJHJJEZ3qlyAcrE/edit#slide=id.g11b2897a1a_2_0) This change, coupled with a new Mozilla Learning wordmark, will aim to lesson confusion (teach in the URL, but Mozilla Learning branding on the site). 

PS @xmatthewx I don't think we need a formal community announcement about the change of the URL. We can start to socialize it more via social media, blog posts, etc.

**Comment by cadecairos** [comment]
milestone can be moved, if this is required sooner.

**Comment by cadecairos** [comment]
I've updated the issue description to include the steps I'll have to take to wrap this task up. I'll take care of it before May 6th.

**Comment by cadecairos** [comment]
Filed IT Bug to get `learning.mozilla.org` set up (employee restricted bug) https://bugzilla.mozilla.org/show_bug.cgi?id=1269860

**Comment by cadecairos** [comment]
Completed!
