### ISSUE TITLE
Create go-live on mozilla domain checklist

### ISSUE THREAD

**Issue by simonwex** [MozillaFoundation/mofo-devops#366]
This should be a checklist we follow whenever hosting something on one of our domains.

**Comment by cadecairos** [comment]
We can fit this in the current HB I think.

**Comment by cadecairos** [comment]
Not alll may be applicable, but should be considered for all deployments none-the-less.

- [ ] Conduct an RRA
- [ ] Perform  a Security Review
  - [ ] Does user generated content get displayed in-browser safely?
  - [ ] Does user generated content get stored in any way - is it done safely?
  - [ ] Is PII handled according to Mozilla's Privacy Policy?
  - [ ] If password information is stored, is it done using best practices? (bcrypt/scrypt + salt)
  - [ ] Does the site implement recommended security headers for HTTP requests? (HSTS, XFO, CSP, XCTO, etc)
  - [ ] Do POST/PUT/DELETE requests implement some form of Cross Site Request Forgery protection?
  - [ ] Does it have dependencies with known security vulnerabilities? (nsp, OWASP dependency-check)
- [ ] Does the system/site have adequate automated testing?
- [ ] Is there a contributors.json file present in the source repository, does it provide contact information in the event of an emergency?
- [ ] If automatically deploys, Who can trigger deploys? Should it be limited? (branch/merge protection)
- [ ] Data Storage
  - [ ] Automatic Backups
  - [ ] Not publicly accessible AND/OR Strong Access credentials
- [ ] [node] Is it using an up-to-date LTS version of node?

**Comment by cadecairos** [comment]
@gideonthomas @alicoding Feel free to add in things I haven't thought of yet!

**Comment by gideonthomas** [comment]
I don't know if this is in scope for this doc or not, but what about a point about how to actually request the domain - probably something like "File a devops bug with the requested domain and the checklist to tick-off as tasks are completed"?

**Comment by cadecairos** [comment]
> I don't know if this is in scope for this doc or not, but what about a point about how to actually request the domain - probably something like "File a devops bug with the requested domain and the checklist to tick-off as tasks are completed"?

I'm not sure that quite fits. I envisioned this as more of a checklist for the basic security requirements and best practices, not a guide for requesting a domain (although documenting *what* can be gotten through filing devops issues is a good idea!)
