### ISSUE TITLE
Tranform the DevOps roadmap etherpad into tickets

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#544]
### Details
CC @cadecairos 

We built a roadmap of devops goals for the next year that needs to be transform into ticket and triaged on the board.

- [x] Goals for January 1st => #549 
- [ ] Goals for April 1st
- [ ] Goals for July 1st
- [ ] Goals for October 1st

**Roadmap entries that will transformed into github issues**
April 1st, 2018:
- Whole engineering team involved in on-call rotation
- Unused AWS resources are decommissioned or consolidated
- Migrate 4 WPEngine sites to Private cloud

July 1st, 2018
- Migrate 4 WPEngine sites to Private cloud

October 1st, 2018
- Fully migrated to Private MoCo WPEngine cloud (11 sites?)

**Comment by cadecairos** [comment]
Let's record the etherpad information here.

**Comment by patjouk** [comment]
Closing this. It's not really relevant anymore.
