### ISSUE TITLE
Full inventory of services/resources/etc that we run

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#549]
### Details

Related to #544 

As decided in the [road map](https://public.etherpad-mozilla.org/p/mofo-devops-roadmap), we want to have a complete inventory by January 1st of which services are running, who are managing them, if they are monitored, etc.

Sub tasks:
- [x] Start by inventorying Heroku #545
- [ ] Inventory of resources on AWS #558 
- [x] Identify what is or should be monitored #547
- [x] Write playbooks for sites and services that are monitored by VictorOps #546
- [x] Identify things that can/should be automated + triage into later milestones #548

**Comment by patjouk** [comment]
Closing this for now: that work is happening in other tickets (cleaning AWS bills, etc)
