### ISSUE TITLE
New pontoon workflow, donate edition

### ISSUE THREAD

**Issue by patjouk** [MozillaFoundation/mofo-devops#739]
Since it works for the foundation site, we can use the same pontoon workflow for donate.

Todos:
- [x] Create a repo for the translations. Can you take care of this @TheoChevalier? 
- [x] Create a bucket on s3
- [x] Create a new IAM user with the relevant permissions
- [x] Generate an archive on Travis with the correct paths + upload it to S3
- [x] Update the pontoon bot to get more info in case the tests failed
- [ ] Update the donate stack: change the `post_deploy` step and remove the old `.po` files

**Comment by TheoChevalier** [comment]
Some thoughts from this morning.

While we will probably have a constant flow of code commits for the foundation site and less frequent translation commits, that may be the opposite for the donate site. That could be an issue in the sense that we have many more locales enabled here, resulting in a large volume of translations sitting in the repo for weeks until the next code commit triggers a prod push. Not to mention that these won’t appear on staging either for l10n QA purposes.

@patjouk Is there a way to signal from `donate-l10n` to `donate-wagtail` “Hey, you need to build the project again”, so that it gets deployed by the next daily prod push?

**Comment by patjouk** [comment]
That's a very good point.
The good news is that it's totally possible to trigger a manual build and promote staging to master, even though there's no code change.
Now for the signaling part: it's far from ideal but we do at least one push per week since we have to update dependencies, so translations wouldn't be sitting for weeks. I have a few ideas, from a reminder every two days to fully automate the process, but I need to think about it more.

I'll keep you posted.
