### ISSUE TITLE
Improve high-level documentation

### ISSUE THREAD

**Issue by tomusher** [MozillaFoundation/mofo-devops#807]
While documentation for individual projects is of a high quality and well maintained within project ‘readme’s, high-level documentation on what tools are being used and why they were chosen is lacking. We should make use of wiki or documentation software to prepare and maintain a high-level overview of the development and DevOps activities performed within Mozilla Foundation.

- [x] Set up mkdocs in https://github.com/MozillaFoundation/MoFo-Engineering-Handbook
- [x] Move documentation from https://github.com/MozillaFoundation/mofo-devops to MoFo-Engineering-Handbook
- [ ] @tomusher document systems into engineering handbook, review AWS accounts, and Cinchy stuff
- [ ] Document Cloudflare
  - [ ] Workers
  - [ ] Firewall
  - [ ] DNS Setup
- [ ] Document CloudFront for Donate
- [ ] CI setup (GH actions)
- [ ] Heroku
  - [ ] Review apps(?)
  - [ ] Cron stuff
  - [ ] Foundation hook that builds mozfest (maybe put into docs for foundation site)
- [ ] AWS
  - [ ] Services in use
  - [ ] Describe what each account is for
  - [ ] Cinchy Infra
  - [ ] Common Voice Infra

**Comment by jamilasnell** [comment]
We should probably make an epic for documentation.

**Comment by benhohner** [comment]
- Set up mkdocs in https://github.com/MozillaFoundation/MoFo-Engineering-Handbook
- Move documentation from https://github.com/MozillaFoundation/mofo-devops to MoFo-Engineering-Handbook
- @tomusher document systems into engineering handbook, review AWS accounts, and Cinchy stuff

**Comment by ayahohner** [comment]
Hey @jenntbeard I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_
